<a href="https://colab.research.google.com/github/Prashanth-557/ML-Training/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a=np.random.randint(30,50,15)
a

array([40, 39, 49, 34, 37, 32, 46, 40, 30, 39, 42, 38, 30, 49, 49])

In [ ]:
a.ndim

1

In [ ]:
a[12]

30

In [ ]:
a[-3]

30

In [ ]:
a[13:-3]

array([], dtype=int32)

In [ ]:
58,31,39,59,52,39,39,52


(58, 31, 39, 59, 52, 39, 39, 52)

In [ ]:
a[-2:-10:-1]

array([49, 30, 38, 42, 39, 30, 40, 46])

In [ ]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
b[2,5]

47

In [ ]:
b[5,6]

67

In [ ]:
b[3,4]

65

In [ ]:
b[1:,1:7]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [ ]:
np.random.seed(94)
b=np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [ ]:
b[1:,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [ ]:
b[-6:,-7:-1]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [ ]:
b[2:5:2,1::3]

array([[41, 28, 38],
       [30, 42, 35]])